# Generated by Django 3.1.7 on 2021-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='stories',
            field=models.ManyToManyField(to='story.Story'),
        ),
    ]
