# Generated by Django 3.1.7 on 2021-05-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20210512_1000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date_posted']},
        ),
    ]
