# Generated by Django 3.1.7 on 2021-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_auto_20210611_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='words_count',
            field=models.IntegerField(default=0),
        ),
    ]
