# Generated by Django 3.1.7 on 2021-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_comment_words_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='words_count',
        ),
        migrations.AddField(
            model_name='story',
            name='words_count',
            field=models.IntegerField(default=0),
        ),
    ]
