# Generated by Django 3.1.7 on 2021-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_auto_20210611_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='read_status',
            field=models.BooleanField(default=False),
        ),
    ]
