# Generated by Django 3.1.7 on 2021-06-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20210626_0511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_posted']},
        ),
    ]
