# Generated by Django 3.1.7 on 2021-04-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210429_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='tentang_saya',
        ),
    ]
